import { AppFrame } from "@/app/AppFrame";
import "./admin-dialog.css";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useNotifications } from "@/contexts/NotificationContext";
import { trpc } from "@/lib/trpc";
import { Activity, CheckCircle2, ChevronRight, FileWarning, LayoutDashboard, Loader2, LockKeyhole, RefreshCw, ShieldAlert, ShieldCheck, Trash2, UsersRound, XCircle } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

type Tab = "overview" | "accounts" | "rooms" | "audit" | "system";
const tabItems: { id: Tab; label: string; icon: typeof LayoutDashboard }[] = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "accounts", label: "Accounts", icon: UsersRound }, { id: "rooms", label: "Rooms", icon: LockKeyhole }, { id: "audit", label: "Audit trail", icon: Activity }, { id: "system", label: "System boundary", icon: ShieldCheck }];
const localTime = (value: Date | string | null | undefined) => value ? new Date(value).toLocaleString() : "—";

export function AdminPage() {
  const [, navigate] = useLocation(); const utils = trpc.useUtils(); const { notify } = useNotifications(); const account = trpc.auth.account.useQuery(undefined, { retry: false }); const [tab, setTab] = useState<Tab>("overview"); const isAdmin = Boolean(account.data?.isSuperAdmin && account.data?.emailVerifiedAt);
  const overview = trpc.admin.overview.useQuery(undefined, { enabled: isAdmin, retry: false }); const accounts = trpc.admin.accounts.useQuery(undefined, { enabled: isAdmin, retry: false }); const rooms = trpc.admin.rooms.useQuery(undefined, { enabled: isAdmin, retry: false }); const audit = trpc.admin.audit.useQuery(undefined, { enabled: isAdmin, retry: false });
  const refresh = async () => { await Promise.all([overview.refetch(), accounts.refetch(), rooms.refetch(), audit.refetch()]); notify({ kind: "success", title: "Admin data refreshed", detail: "Only metadata and operational status were refreshed." }); };
  const suspend = trpc.admin.setAccountSuspension.useMutation({ onSuccess: (_, values) => { void utils.admin.accounts.invalidate(); void utils.admin.overview.invalidate(); notify({ kind: values.suspended ? "warning" : "success", title: values.suspended ? "Account suspended" : "Account restored", detail: "Account sessions and future room registry access were updated." }); } });
  const revoke = trpc.admin.revokeMembership.useMutation({ onSuccess: () => { void utils.admin.rooms.invalidate(); notify({ kind: "warning", title: "Room membership revoked", detail: "Future registry access is blocked. Direct peers may persist until reconnect." }); } });
  const deleteRoom = trpc.admin.deleteRoom.useMutation({ onSuccess: () => { void utils.admin.rooms.invalidate(); void utils.admin.overview.invalidate(); notify({ kind: "warning", title: "Room registry removed", detail: "Only server metadata was deleted; no document content was accessed." }); } });
  const permanentlyDelete = trpc.admin.permanentlyDeleteAccount.useMutation({ onSuccess: () => { void utils.admin.accounts.invalidate(); void utils.admin.rooms.invalidate(); void utils.admin.audit.invalidate(); void utils.admin.overview.invalidate(); notify({ kind: "warning", title: "Account permanently deleted", detail: "Sessions, tokens, account-linked room memberships, and account metadata were removed. Browser-local documents remain outside Peerlock." }); } });
  if (account.isLoading) return <AdminState icon={<Loader2 className="spin" size={23} />} title="Checking control-center access" detail="The server is validating the signed-in account." />;
  if (!isAdmin) return <AppFrame><AdminState icon={<ShieldAlert size={24} />} title="Super-admin access only" detail="This area is available only to the single server-configured, verified administrator account. No other account can access it." action="Go to account" onAction={() => navigate("/account/sign-in")} /></AppFrame>;
  const metrics = overview.data?.metrics;
  return <AppFrame><main className="admin-page"><aside className="admin-rail"><div className="admin-brand"><ShieldCheck size={20} /><span>PEERLOCK</span><b>Control center</b></div><p>One configured super-admin. Metadata only. Every action is recorded.</p><nav>{tabItems.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={tab === item.id ? "active" : ""}><item.icon size={16} />{item.label}<ChevronRight size={14} /></button>)}</nav><div className="admin-boundary"><LockKeyhole size={16} /><span>Documents, chats, passwords, OTPs, and room secrets are excluded.</span></div></aside><section className="admin-workspace"><header className="admin-header"><div><p className="eyebrow">SUPER ADMIN / CONTROL PLANE</p><h1>Operate the workspace,<br /><em>not its private content.</em></h1></div><button className="admin-refresh" onClick={() => void refresh()}><RefreshCw size={16} />Refresh data</button></header>{tab === "overview" && <Overview metrics={metrics} audit={overview.data?.recentAudits ?? []} onTab={setTab} />}{tab === "accounts" && <AccountsPanel accounts={accounts.data ?? []} currentId={account.data!.id} onSuspend={(accountId, suspended) => suspend.mutate({ accountId, suspended, reason: suspended ? "Suspended by super administrator" : undefined })} onDelete={accountId => permanentlyDelete.mutate({ accountId })} busy={suspend.isPending || permanentlyDelete.isPending} />}{tab === "rooms" && <RoomsPanel rooms={rooms.data ?? []} onRevoke={(roomId, membershipId) => revoke.mutate({ roomId, membershipId })} onDelete={roomId => deleteRoom.mutate({ roomId })} busy={revoke.isPending || deleteRoom.isPending} />}{tab === "audit" && <AuditPanel rows={audit.data ?? []} />}{tab === "system" && <SystemPanel onOpen={() => navigate("/devlogs")} />}</section></main></AppFrame>;
}

function AdminState({ icon, title, detail, action, onAction }: { icon: React.ReactNode; title: string; detail: string; action?: string; onAction?: () => void }) { return <main className="admin-state"><div>{icon}<p className="eyebrow">PEERLOCK / CONTROL CENTER</p><h1>{title}</h1><p>{detail}</p>{action && <button onClick={onAction}>{action}</button>}</div></main>; }
function Overview({ metrics, audit, onTab }: { metrics: any; audit: any[]; onTab: (tab: Tab) => void }) { const cards = [{ label: "Accounts", value: metrics?.accounts, caption: `${metrics?.unverified ?? 0} awaiting verification`, tab: "accounts" as Tab, icon: UsersRound }, { label: "Rooms", value: metrics?.rooms, caption: "metadata registry only", tab: "rooms" as Tab, icon: LockKeyhole }, { label: "Suspended", value: metrics?.suspended, caption: "sessions revoked", tab: "accounts" as Tab, icon: ShieldAlert }]; return <><section className="admin-metrics admin-metrics-focused">{cards.map(card => <button key={card.label} onClick={() => onTab(card.tab)}><span><card.icon size={17} />{card.label}</span><b>{card.value ?? "—"}</b><small>{card.caption}</small></button>)}</section><section className="admin-overview-grid"><article className="admin-feature"><p className="eyebrow">PRIVACY CONTROL</p><h2>Operational visibility,<br />zero content visibility.</h2><p>Manage account identity, registry permissions, system health, and audit events without ever loading a document body, chat message, password, OTP, password hash, or WebRTC secret.</p><div><ShieldCheck size={16} /> Metadata-only by architecture</div></article><article className="admin-audit-preview"><header><div><p className="eyebrow">LATEST ADMIN EVENTS</p><h2>Accountable operations</h2></div><button onClick={() => onTab("audit")}>Open audit</button></header>{audit.length ? audit.map(item => <div key={item.id}><span>{item.action.replace(".", " · ")}</span><p>{item.summary}</p><small>{localTime(item.createdAt)}</small></div>) : <p className="admin-empty">No administrative actions have been recorded yet.</p>}</article></section></>; }
function AccountsPanel({ accounts, currentId, onSuspend, onDelete, busy }: { accounts: any[]; currentId: string; onSuspend: (id: string, suspended: boolean) => void; onDelete: (id: string) => void; busy: boolean }) { const [pendingDelete, setPendingDelete] = useState<string | null>(null); return <><section className="admin-panel"><header><div><p className="eyebrow">ACCOUNT CONTROL</p><h2>Identity and access lifecycle</h2><p>Suspension revokes account sessions and prevents future room registry access. Permanent delete removes server account metadata so the email and username can register again; browser-local documents remain private on the device.</p></div></header><div className="admin-table">{accounts.map(row => <article key={row.id}><div className="admin-person"><b>{row.username}</b><span>{row.email}</span><small>{row.isSuperAdmin ? "Configured super admin" : row.emailVerifiedAt ? "Verified" : "Pending verification"}</small></div><div><span className={`admin-status ${row.suspendedAt ? "danger" : "good"}`}>{row.suspendedAt ? "Suspended" : "Active"}</span><small>Last sign-in: {localTime(row.lastSignedInAt)}</small></div><div className="admin-account-actions">{row.id === currentId ? <span className="admin-lock">Protected</span> : <><button className={row.suspendedAt ? "admin-button secondary" : "admin-button danger"} disabled={busy} onClick={() => onSuspend(row.id, !row.suspendedAt)}>{row.suspendedAt ? "Restore" : "Suspend"}</button><button className="admin-delete-user" disabled={busy} onClick={() => setPendingDelete(row.id)}><Trash2 size={13} />Delete user</button></>}</div></article>)}</div></section><AdminDeleteDialog open={Boolean(pendingDelete)} busy={busy} title="Permanently delete this account?" detail="This removes account metadata, sessions, tokens, and account-linked room memberships. Browser-local documents cannot be deleted remotely." action="Delete account" onClose={() => setPendingDelete(null)} onConfirm={() => { if (pendingDelete) onDelete(pendingDelete); setPendingDelete(null); }} /></>; }
function RoomsPanel({ rooms, onRevoke, onDelete, busy }: { rooms: any[]; onRevoke: (roomId: string, membershipId: string) => void; onDelete: (roomId: string) => void; busy: boolean }) { const [open, setOpen] = useState<string | null>(null); const [pendingDelete, setPendingDelete] = useState<string | null>(null); return <><section className="admin-panel"><header><div><p className="eyebrow">ROOM REGISTRY</p><h2>Encrypted rooms, metadata only</h2><p>Peerlock never stores document text or chat messages. These controls affect future metadata-registry access only.</p></div></header><div className="admin-table room-table">{rooms.map(room => <article key={room.id}><div><b>Room {room.code}</b><span>{room.protected ? "Password-protected" : "Open room"}</span><small>Last registry activity: {localTime(room.lastActivityAt)}</small></div><div><span className="admin-status good">{room.memberships.approved} approved</span><small>{room.memberships.pending} pending request{room.memberships.pending === 1 ? "" : "s"}</small></div><div className="admin-room-actions"><button className="admin-button secondary" onClick={() => setOpen(open === room.id ? null : room.id)}>Members</button><button className="admin-button danger" disabled={busy} onClick={() => setPendingDelete(room.id)}>Delete registry</button></div>{open === room.id && <section className="admin-members">{room.memberships.entries.map((member: any) => <div key={member.id}><span><b>{member.displayName}</b><small>{member.status} · seen {localTime(member.lastSeenAt)}</small></span><button disabled={busy || member.status === "declined"} onClick={() => onRevoke(room.id, member.id)}>Revoke</button></div>)}</section>}</article>)}</div></section><AdminDeleteDialog open={Boolean(pendingDelete)} busy={busy} title="Delete this room registry?" detail="Only room registry metadata is removed. Documents and independent browser copies are never accessed or deleted." action="Delete registry" onClose={() => setPendingDelete(null)} onConfirm={() => { if (pendingDelete) onDelete(pendingDelete); setPendingDelete(null); }} /></>; }
function AdminDeleteDialog({ open, busy, title, detail, action, onClose, onConfirm }: { open: boolean; busy: boolean; title: string; detail: string; action: string; onClose: () => void; onConfirm: () => void }) { return <AlertDialog open={open} onOpenChange={value => { if (!value) onClose(); }}><AlertDialogContent className="admin-destructive-dialog"><AlertDialogHeader><p className="eyebrow">IRREVERSIBLE SERVER METADATA ACTION</p><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{detail}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep it</AlertDialogCancel><AlertDialogAction disabled={busy} className="admin-destructive-confirm" onClick={onConfirm}>{busy ? "Working…" : action}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
function AuditPanel({ rows }: { rows: any[] }) { return <section className="admin-panel"><header><div><p className="eyebrow">IMMUTABLE AUDIT TRAIL</p><h2>Every control action is accountable</h2><p>This metadata-only record excludes personal credentials, document data, chat data, and server secrets.</p></div></header><div className="admin-audit-list">{rows.length ? rows.map(row => <article key={row.id}><Activity size={15} /><div><b>{row.action.replace(".", " · ")}</b><p>{row.summary}</p></div><small>{localTime(row.createdAt)}</small></article>) : <p className="admin-empty">No admin actions have been logged yet.</p>}</div></section>; }
function SystemPanel({ onOpen }: { onOpen: () => void }) { return <section className="admin-system"><div><CheckCircle2 size={22} /><p className="eyebrow">SECURITY BOUNDARY</p><h2>What the super admin can and cannot manage.</h2></div><div className="admin-boundary-grid"><article><ShieldCheck size={17} /><b>Can manage</b><p>Accounts, verification states, suspension, account sessions, room registry metadata, audit events, and deployment readiness.</p></article><article><XCircle size={17} /><b>Cannot access</b><p>Document bodies, editor updates, chat messages, passwords, password hashes, OTPs, reset tokens, database URLs, API keys, or WebRTC transport secrets.</p></article></div><button className="admin-button primary" onClick={onOpen}><FileWarning size={15} />Open public system diagnostics</button></section>; }
