import { CheckCircle2, ClipboardCheck, Copy, FileWarning, LockKeyhole, RefreshCw, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";

type Snapshot = { generatedAt: string; access: { authenticated: boolean; verified: boolean; accountReference: string }; runtime: Record<string, unknown>; database: { provider: string; urlLooksValid: boolean; expectedMigrations: string[]; tables: Record<string, unknown> }; email: { configured: boolean; senderConfigured: boolean; appBaseUrlConfigured: boolean; lastAttemptAt: string | null; lastDelivery: string; providerStatus: number | null; safeReason: string | null }; authentication: Record<string, unknown>; collaboration: Record<string, unknown>; privacy: Record<string, unknown> };
function pretty(value: unknown) { return JSON.stringify(value, null, 2); }

export function DevLogsPage() {
  const [, navigate] = useLocation(); const account = trpc.auth.account.useQuery(undefined, { retry: false }); const diagnostics = trpc.diagnostics.snapshot.useQuery(undefined, { enabled: Boolean(account.data?.emailVerifiedAt), retry: false, refetchInterval: 20_000 }); const [copied, setCopied] = useState(false);
  const report = useMemo(() => diagnostics.data ? pretty(diagnostics.data) : "", [diagnostics.data]);
  const copy = async () => { if (!report) return; await navigator.clipboard.writeText(report); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  if (account.isLoading) return <DevLogsState icon={<RefreshCw className="spin" size={22} />} title="Checking diagnostics access" text="Confirming your protected Peerlock account." />;
  if (!account.data) return <DevLogsState icon={<LockKeyhole size={22} />} title="Sign in required" text="Development diagnostics are available only to verified Peerlock accounts." action="Go to account" onAction={() => navigate("/account/sign-in")} />;
  if (!account.data.emailVerifiedAt) return <DevLogsState icon={<ShieldCheck size={22} />} title="Verify your email first" text="Diagnostics are protected by the same verified account requirement as rooms and documents." action="Verify account" onAction={() => navigate("/account/sign-in")} />;
  if (diagnostics.isLoading) return <DevLogsState icon={<RefreshCw className="spin" size={22} />} title="Collecting safe diagnostics" text="Checking runtime, database tables, email delivery, and collaboration metadata. No documents are read." />;
  if (!diagnostics.data) return <DevLogsState icon={<FileWarning size={22} />} title="Diagnostics unavailable" text={diagnostics.error?.message ?? "The server could not provide a safe diagnostic snapshot."} action="Try again" onAction={() => void diagnostics.refetch()} />;
  const data = diagnostics.data as Snapshot;
  const rows = [
    ["Runtime", data.runtime], ["Database schema", data.database], ["Email delivery", data.email], ["Authentication", data.authentication], ["Collaboration", data.collaboration], ["Privacy exclusions", data.privacy],
  ] as const;
  return <main className="devlogs-page"><header className="devlogs-header"><div><p className="eyebrow">PEERLOCK / PROTECTED DEVELOPMENT DIAGNOSTICS</p><h1>System status,<br /><em>without secrets.</em></h1><p>Detailed operational data for troubleshooting. This page never returns passwords, tokens, OTP codes, database URLs, email keys, document contents, or chat text.</p></div><div className="devlogs-actions"><button onClick={() => void diagnostics.refetch()} disabled={diagnostics.isFetching}><RefreshCw className={diagnostics.isFetching ? "spin" : ""} size={16} /> Refresh</button><button className="devlogs-copy" onClick={() => void copy()} disabled={!report}>{copied ? <ClipboardCheck size={16} /> : <Copy size={16} />}{copied ? "Copied safe report" : "Copy safe report"}</button></div></header><section className="devlogs-overview"><div><span>Access</span><b><CheckCircle2 size={15} />Verified account</b><small>{data.access.accountReference}</small></div><div><span>Generated</span><b>{new Date(data.generatedAt).toLocaleString()}</b><small>Refreshes every 20 seconds while open</small></div><div><span>Database</span><b className={data.database.urlLooksValid ? "good" : "bad"}>{data.database.urlLooksValid ? "Neon URL valid" : "Configuration needs attention"}</b><small>{data.database.provider}</small></div><div><span>Email</span><b className={data.email.lastDelivery === "Accepted by provider" ? "good" : data.email.lastDelivery === "No attempt during this process" ? "neutral" : "bad"}>{data.email.lastDelivery}</b><small>{data.email.safeReason ?? "No failure recorded"}</small></div></section><section className="devlogs-grid">{rows.map(([title, value]) => <article key={title}><header><h2>{title}</h2><button onClick={() => void navigator.clipboard.writeText(pretty(value))}><Copy size={14} />Copy section</button></header><pre>{pretty(value)}</pre></article>)}</section><section className="devlogs-boundary"><ShieldCheck size={18} /><p><b>Safe by design.</b> The snapshot contains counts and configuration state only. It intentionally excludes all private text, credentials, account secrets, and message bodies.</p></section></main>;
}

function DevLogsState({ icon, title, text, action, onAction }: { icon: React.ReactNode; title: string; text: string; action?: string; onAction?: () => void }) { return <main className="devlogs-state"><div>{icon}<p className="eyebrow">PEERLOCK / DEVLOGS</p><h1>{title}</h1><p>{text}</p>{action && <button onClick={onAction}>{action}</button>}</div></main>; }
