import { CheckCircle2, ClipboardCheck, Copy, FileWarning, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { useNotifications } from "@/contexts/NotificationContext";

type Snapshot = { generatedAt: string; access: { publicReadOnly: boolean; authenticationRequiredForWorkspace: boolean }; runtime: Record<string, unknown>; database: { provider: string; urlLooksValid: boolean; expectedMigrations: string[]; tables: Record<string, unknown> }; email: { configured: boolean; senderConfigured: boolean; appBaseUrlConfigured: boolean; lastAttemptAt: string | null; lastDelivery: string; providerStatus: number | null; safeReason: string | null }; authentication: Record<string, unknown>; collaboration: Record<string, unknown>; privacy: Record<string, unknown> };
function pretty(value: unknown) { return JSON.stringify(value, null, 2); }

export function DevLogsPage() {
  const diagnostics = trpc.diagnostics.snapshot.useQuery(undefined, { retry: false, refetchInterval: 20_000 }); const { notify } = useNotifications(); const [copied, setCopied] = useState(false); const [checkDelayed, setCheckDelayed] = useState(false); const report = useMemo(() => diagnostics.data ? pretty(diagnostics.data) : "", [diagnostics.data]);
  useEffect(() => { if (!diagnostics.isLoading) { setCheckDelayed(false); return; } const timeout = window.setTimeout(() => setCheckDelayed(true), 8000); return () => window.clearTimeout(timeout); }, [diagnostics.isLoading]);
  const copySafe = async (text: string, label: string) => { if (!text) return; try { await navigator.clipboard.writeText(text); setCopied(label === "report"); if (label === "report") window.setTimeout(() => setCopied(false), 1800); notify({ kind: "success", title: label === "report" ? "Safe report copied" : `${label} copied`, detail: "Only the displayed redacted diagnostic information was copied." }); } catch { notify({ kind: "error", title: "Copy unavailable", detail: "Your browser blocked clipboard access. Select the displayed text and copy it manually." }); } };
  const refresh = async () => { const result = await diagnostics.refetch(); notify(result.error ? { kind: "error", title: "Status refresh unavailable", detail: "The public diagnostic snapshot could not be refreshed." } : { kind: "success", title: "Status refreshed", detail: "The public redacted system snapshot is current." }); };
  if (diagnostics.isLoading && !checkDelayed) return <DevLogsState icon={<RefreshCw className="spin" size={22} />} title="Collecting public status" text="Checking runtime, database tables, email delivery, and collaboration metadata. No documents are read." />;
  if (diagnostics.isLoading) return <DevLogsState icon={<FileWarning size={22} />} title="Status check is delayed" text="The public, redacted status check is taking longer than expected. No private content has been read." action="Try again" onAction={() => void refresh()} />;
  if (!diagnostics.data) return <DevLogsState icon={<FileWarning size={22} />} title="Diagnostics unavailable" text="The server could not provide a safe diagnostic snapshot. Try again shortly; detailed errors stay private by design." action="Try again" onAction={() => void refresh()} />;
  const data = diagnostics.data as Snapshot; const rows = [["Runtime", data.runtime], ["Database schema", data.database], ["Email delivery", data.email], ["Authentication", data.authentication], ["Collaboration", data.collaboration], ["Privacy exclusions", data.privacy]] as const;
  return <main className="devlogs-page"><header className="devlogs-header"><div><p className="eyebrow">PEERLOCK / PUBLIC SYSTEM STATUS</p><h1>System status,<br /><em>without secrets.</em></h1><p>Public, read-only deployment diagnostics for troubleshooting. This page never returns account details, passwords, tokens, OTP codes, database URLs, email keys, document contents, or chat text.</p></div><div className="devlogs-actions"><button onClick={() => void refresh()} disabled={diagnostics.isFetching}><RefreshCw className={diagnostics.isFetching ? "spin" : ""} size={16} /> Refresh</button><button className="devlogs-copy" onClick={() => void copySafe(report, "report")} disabled={!report}>{copied ? <ClipboardCheck size={16} /> : <Copy size={16} />}{copied ? "Copied safe report" : "Copy safe report"}</button></div></header><section className="devlogs-overview"><div><span>Visibility</span><b><CheckCircle2 size={15} />Public / read-only</b><small>Workspace remains account-only</small></div><div><span>Generated</span><b>{new Date(data.generatedAt).toLocaleString()}</b><small>Refreshes every 20 seconds while open</small></div><div><span>Database</span><b className={data.database.urlLooksValid ? "good" : "bad"}>{data.database.urlLooksValid ? "Neon URL valid" : "Configuration needs attention"}</b><small>{data.database.provider}</small></div><div><span>Email</span><b className={data.email.lastDelivery === "Accepted by provider" ? "good" : data.email.lastDelivery === "No attempt during this process" ? "neutral" : "bad"}>{data.email.lastDelivery}</b><small>{data.email.safeReason ?? "No failure recorded"}</small></div></section><section className="devlogs-grid">{rows.map(([title, value]) => <article key={title}><header><h2>{title}</h2><button onClick={() => void copySafe(pretty(value), title)}><Copy size={14} />Copy section</button></header><pre>{pretty(value)}</pre></article>)}</section><section className="devlogs-boundary"><ShieldCheck size={18} /><p><b>Safe by design.</b> The public snapshot contains aggregate readiness and configuration state only. It intentionally excludes every private text field, credential, account secret, and message body.</p></section></main>;
}
function DevLogsState({ icon, title, text, action, onAction }: { icon: React.ReactNode; title: string; text: string; action?: string; onAction?: () => void }) { return <main className="devlogs-state"><div>{icon}<p className="eyebrow">PEERLOCK / PUBLIC STATUS</p><h1>{title}</h1><p>{text}</p>{action && <button onClick={onAction}>{action}</button>}</div></main>; }
