import { AppFrame, RoomBadge } from "@/app/AppFrame";
import { ProfileGate } from "@/app/ProfileGate";
import { useWorkspace } from "@/app/WorkspaceProvider";
import { ArrowUpRight, FilePlus2, Link2, Trash2 } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import "./guest-room-access.css";

export function HubPage() {
  const [, navigate] = useLocation(); const { documents, loading, createDocument, removeDocument, profile } = useWorkspace(); const [roomCode, setRoomCode] = useState(""); const [roomPassword, setRoomPassword] = useState(""); const [protectedRoom, setProtectedRoom] = useState(false); const [joinError, setJoinError] = useState(""); const liveRooms = trpc.room.liveCount.useQuery(undefined, { refetchInterval: 15000 });
  const create = async () => { const document = await createDocument(); navigate(`/studio/${document.id}`); };
  const join = (event: React.FormEvent) => { event.preventDefault(); setJoinError(""); if (!/^[A-Z0-9]{8}$/i.test(roomCode)) { setJoinError("Enter the eight-character code from a real room invite."); return; } if (protectedRoom && roomPassword.trim().length < 8) { setJoinError("Enter the password selected by the room owner."); return; } const code = roomCode.toUpperCase(); if (protectedRoom) sessionStorage.setItem(`peerlock-room-password:${code}`, roomPassword.trim()); navigate(`/r/${code}${protectedRoom ? "?access=protected" : ""}`); };
  return <ProfileGate><AppFrame><div className="hub-layout"><section className="hub-intro"><div><p className="eyebrow">Your workspace · {liveRooms.data ?? 0} live rooms</p><h1>Documents<br />without a cloud.</h1><p>Every draft starts in this browser. A room is created only through the verified room registry, then its document syncs directly between approved peers.</p></div><div className="hub-actions"><button onClick={() => void create()}><FilePlus2 size={18} />Start a note</button><button onClick={() => document.getElementById("join-room")?.scrollIntoView({ behavior: "smooth" })}><Link2 size={18} />Join a room</button></div></section><section className="document-library"><header><div><p className="eyebrow">Local library</p><h2>Open work</h2></div><span>{String(documents.length).padStart(2, "0")} items</span></header>{loading ? <p className="loading">Opening local index…</p> : documents.length ? <div className="document-grid">{documents.map(document => <article key={document.id}><button className="document-card-main" onClick={() => navigate(`/studio/${document.id}`)}><span className="document-card-type">{document.roomId ? (document.roomProtected ? "Password room" : "Open room") : "Private draft"}</span><h3>{document.title}</h3><p>Updated {new Date(document.updatedAt).toLocaleDateString()}</p><RoomBadge connected={Boolean(document.roomId)} /><ArrowUpRight size={18} /></button><button className="delete-note" onClick={() => { if (confirm(`Remove “${document.title}” from this browser?`)) void removeDocument(document.id); }} aria-label={`Remove ${document.title}`}><Trash2 size={15} /></button></article>)}</div> : <div className="empty-library"><span>Nothing saved here yet.</span><h3>Start with a single private thought.</h3><button onClick={() => void create()}>Create first note <ArrowUpRight size={16} /></button></div>}</section><section id="join-room" className="join-room"><div><p className="eyebrow">Verified room entry</p><h2>Request access to a room.</h2><p>Unknown codes are rejected by the room registry. Protected rooms verify the owner’s password before sending a join request.</p></div><form onSubmit={join}><label>Room code<input value={roomCode} onChange={event => { setRoomCode(event.target.value.toUpperCase()); setJoinError(""); }} maxLength={8} placeholder="AB12CD34" /></label><label className="room-protection-choice"><input type="checkbox" checked={protectedRoom} onChange={event => { setProtectedRoom(event.target.checked); setJoinError(""); }} />This room has a password</label>{protectedRoom && <label>Room password<input type="password" value={roomPassword} onChange={event => { setRoomPassword(event.target.value); setJoinError(""); }} placeholder="Enter the password" /></label>}{joinError && <p className="join-error" role="alert">{joinError}</p>}<button type="submit" disabled={!profile}>Request access <ArrowUpRight size={16} /></button></form></section></div></AppFrame></ProfileGate>;
}
