import { AppShell } from "@/components/AppShell";
import { ConnectionGraph } from "@/components/ConnectionGraph";
import { BadgeCheck, BookOpenCheck, Boxes, DatabaseZap, ExternalLink, LockKeyhole, Network, ShieldAlert, ShieldCheck, Wifi } from "lucide-react";

const references = [
  { label: "Yjs: Offline Support", url: "https://docs.yjs.dev/getting-started/allowing-offline-editing" },
  { label: "y-indexeddb provider", url: "https://github.com/yjs/y-indexeddb" },
  { label: "y-webrtc connector", url: "https://github.com/yjs/y-webrtc" },
  { label: "Tiptap: Awareness", url: "https://tiptap.dev/docs/collaboration/core-concepts/awareness" },
];

function Citation({ number }: { number: number }) {
  const reference = references[number - 1];
  if (!reference) return null;
  return <a href={reference.url} target="_blank" rel="noreferrer" className="ml-1 inline-flex font-mono text-[10px] font-semibold text-[#7FE6CA] hover:text-white" aria-label={`Reference ${number}: ${reference.label}`}>[{number}]</a>;
}

export default function ReportPage() {
  return <AppShell><article className="mx-auto max-w-5xl pb-14">
    <header className="rounded-3xl border border-white/[0.09] bg-[#111722]/76 px-6 py-8 sm:px-9 sm:py-10"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#7FE6CA]">MCA academic submission · system report</p><h1 className="mt-4 max-w-3xl text-3xl font-semibold tracking-[-0.05em] text-white sm:text-[42px]">Peer-to-Peer Encrypted Workspace</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-[#9BA8BD]">A local-first collaborative document editor using conflict-free replicated data types, encrypted WebRTC data channels, and browser-resident persistence.</p><div className="mt-6 flex flex-wrap gap-2">{["Distributed systems", "CRDTs", "WebRTC", "Offline-first", "Privacy engineering"].map(tag => <span key={tag} className="rounded-full border border-white/[0.11] bg-white/[0.035] px-3 py-1 text-[11px] font-medium text-[#C6D1DF]">{tag}</span>)}</div></header>
    <section className="mt-7 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-3xl border border-white/[0.08] bg-[#101620]/72 p-6"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#7FE6CA]">Abstract</p><p className="mt-4 text-sm leading-7 text-[#BDC7D7]">This project investigates whether a small collaborative editor can preserve the useful real-time behavior of cloud document tools while minimizing central trust. Each browser maintains its own Yjs replica, persists local updates in IndexedDB, and exchanges mergeable operations directly with other participants through WebRTC. A signaling relay assists discovery but is intentionally excluded from document storage and editing paths.<Citation number={3} /></p><p className="mt-4 text-sm leading-7 text-[#BDC7D7]">The system targets groups of up to ten peers, where a browser-to-browser mesh remains appropriate. The design demonstrates eventual consistency, offline recovery, conflict-free convergence, awareness propagation, and explicit trust-boundary communication.<Citation number={4} /></p></div><ConnectionGraph peers={[{ clientId: "local", name: "You", color: "#71E4C2", isLocal: true }, { clientId: "peer-a", name: "Peer A", color: "#A99FF7" }, { clientId: "peer-b", name: "Peer B", color: "#F4B860" }]} connectionState="synced" /></section>
    <section className="mt-5 grid gap-3 rounded-3xl border border-white/[0.08] bg-[#101620]/72 p-5 sm:grid-cols-3"><p className="text-xs leading-5 text-[#99A7BA]"><strong className="text-[#E9EEF6]">Local persistence.</strong> The Y IndexedDB adapter persists the shared Yjs document inside the browser, allowing offline edits to survive a refresh or lost network connection.<Citation number={1} /><Citation number={2} /></p><p className="text-xs leading-5 text-[#99A7BA]"><strong className="text-[#E9EEF6]">Peer transport.</strong> The y-webrtc provider propagates Yjs document updates through WebRTC peers and supports a password to protect communication over untrusted signaling infrastructure.<Citation number={3} /></p><p className="text-xs leading-5 text-[#99A7BA]"><strong className="text-[#E9EEF6]">Live awareness.</strong> Presence metadata such as names, colors, cursor positions, and selections is designed to be ephemeral rather than part of the document history.<Citation number={4} /></p></section>
    <section className="mt-7 grid gap-5 md:grid-cols-2"><div className="report-card"><Boxes className="report-icon text-[#B7AEFF]" /><h2>1. System architecture</h2><p>The browser application owns the editor state. Tiptap renders the rich-text interface over a Yjs shared document. `y-indexeddb` writes each local update to IndexedDB; `y-webrtc` propagates the same CRDT updates through direct WebRTC data channels after a signaling-assisted handshake. The application host serves static application assets only and has no document-content endpoint.</p></div><div className="report-card"><Network className="report-icon text-[#77E6C5]" /><h2>2. WebRTC signaling flow</h2><p>Peers first connect to a lightweight signaling service to exchange the temporary information needed to form a WebRTC connection. Once the peer connection opens, Yjs updates travel along the encrypted data channel. The signaling step is not a document-sync step; it cannot provide document history, editing APIs, or cloud backup in this architecture.</p></div><div className="report-card"><DatabaseZap className="report-icon text-[#78C8F6]" /><h2>3. CRDT convergence</h2><p>A CRDT allows replicas to be edited independently and later merged without a central conflict resolver. Instead of locking a paragraph or applying “last writer wins,” Yjs records operations that are designed to merge deterministically. This supports concurrent edits, temporary disconnection, and later reconnection.</p></div><div className="report-card"><Wifi className="report-icon text-[#F4C477]" /><h2>4. Offline-first behavior</h2><p>Offline work is not a special mode. The document is restored from IndexedDB at startup and every local edit is persisted there. When a valid peer connection becomes available again, the provider exchanges missing updates and replicas converge. The local browser remains usable when no relay or peer is currently reachable.</p></div></section>
    <section className="mt-7 rounded-3xl border border-white/[0.08] bg-[#101620]/72 p-6 sm:p-8"><div className="flex gap-3"><LockKeyhole className="mt-0.5 h-5 w-5 shrink-0 text-[#7FE6CA]" /><div><h2 className="text-lg font-semibold tracking-[-0.025em] text-white">Security and privacy model</h2><p className="mt-3 text-sm leading-7 text-[#B8C3D4]">An invite contains a short room code and a randomly generated 256-bit secret. The secret is placed in the URL fragment, which browsers do not include in HTTP requests. The browser derives an opaque room name from the code and secret, then supplies the secret to `y-webrtc` to protect signaling communication. WebRTC data channels encrypt peer transport. Therefore document data is never deliberately transmitted to, or stored by, this application server.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[{ title: "In scope", text: "Document content is held in browser storage and peer browsers; the application server has no document body route.", icon: ShieldCheck, tone: "text-[#7FE6CA]" }, { title: "Metadata limitation", text: "Signaling, STUN/TURN, and network providers may observe connection timing and network identifiers.", icon: BadgeCheck, tone: "text-[#F4C477]" }, { title: "Endpoint limitation", text: "A compromised browser, leaked invite secret, or insecure device can expose local content.", icon: ShieldAlert, tone: "text-[#FF9EAE]" }].map(item => <div key={item.title} className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4"><item.icon className={`h-4 w-4 ${item.tone}`} /><h3 className="mt-3 text-xs font-semibold text-[#E4EAF4]">{item.title}</h3><p className="mt-1.5 text-[11px] leading-5 text-[#8491A6]">{item.text}</p></div>)}</div></section>
    <section className="mt-7 rounded-3xl border border-white/[0.08] bg-[#101620]/72 p-6 sm:p-8"><BookOpenCheck className="h-5 w-5 text-[#B7AEFF]" /><h2 className="mt-4 text-lg font-semibold tracking-[-0.025em] text-white">Conclusion and future scope</h2><p className="mt-3 text-sm leading-7 text-[#B8C3D4]">The project validates a privacy-first alternative for small-group collaboration. Its technical contribution is not that it eliminates all infrastructure; signaling and network traversal may still be necessary. Instead, it narrows the trusted role of infrastructure so that document content is not centralised. Future work could include self-hosted signaling, encrypted local backup chosen by the user, key rotation, access revocation, document attachments, and formal performance measurement under simulated peer churn.</p></section>
    <section className="mt-7 rounded-3xl border border-white/[0.08] bg-[#101620]/72 p-6 sm:p-8"><h2 className="text-lg font-semibold text-white">References</h2><ol className="mt-4 space-y-3">{references.map((reference, index) => <li key={reference.url} className="flex gap-3 text-sm text-[#9CA9BE]"><span className="font-mono text-[#7FE6CA]">[{index + 1}]</span><a href={reference.url} target="_blank" rel="noreferrer" className="group inline-flex items-center gap-1 hover:text-white">{reference.label}<ExternalLink className="h-3.5 w-3.5 text-[#6E7B92] group-hover:text-[#7FE6CA]" /></a></li>)}</ol></section>
  </article></AppShell>;
}
