import { ProfileGate } from "@/app/ProfileGate";
import { useWorkspace } from "@/app/WorkspaceProvider";
import { readInvite } from "@/features/room/invite";
import { trpc } from "@/lib/trpc";
import { ArrowRight, KeyRound, Radio, ShieldCheck, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";

export function RoomRoute() {
  const [, navigate] = useLocation(); const { profile, openRoom } = useWorkspace(); const invite = readInvite();
  const [password, setPassword] = useState(() => { const code = readInvite()?.roomCode; return code ? sessionStorage.getItem(`peerlock-room-password:${code}`) ?? "" : ""; }); const [roomId, setRoomId] = useState(""); const [error, setError] = useState(""); const [requiresPassword, setRequiresPassword] = useState(Boolean(invite?.protected)); const [joinRequested, setJoinRequested] = useState(true);
  const request = trpc.room.requestJoin.useMutation({ onSuccess: value => { const transportSecret = value.state === "approved" && "transportSecret" in value ? value.transportSecret : undefined; if (transportSecret) void openRoom({ id: value.roomId, code: value.code, protected: value.protected, transportSecret }).then(document => navigate(`/studio/${document.id}`)); else setRoomId(value.roomId); }, onError: issue => { if (issue.message.toLowerCase().includes("password")) { setRequiresPassword(true); setPassword(""); setError(""); } else setError(issue.message); } });
  const access = trpc.room.access.useQuery({ roomId }, { enabled: Boolean(roomId), retry: false, refetchInterval: roomId ? 750 : false });
  useEffect(() => { if (!roomId) return; const stream = new EventSource(`/api/room-events/${roomId}`); stream.onmessage = () => void access.refetch(); return () => stream.close(); }, [roomId]);
  useEffect(() => { if (!joinRequested || !profile || !invite || request.isPending || roomId) return; if (requiresPassword && password.length < 8) { setJoinRequested(false); return; } setJoinRequested(false); request.mutate({ code: invite.roomCode, password: requiresPassword ? password : undefined, identity: { name: profile.name || `Guest ${profile.id.slice(0, 4)}`, color: profile.color } }); if (requiresPassword) sessionStorage.removeItem(`peerlock-room-password:${invite.roomCode}`); }, [joinRequested, profile?.id, invite?.roomCode, requiresPassword, password, roomId]);
  useEffect(() => { const transportSecret = access.data?.state === "approved" && "transportSecret" in access.data ? access.data.transportSecret : undefined; if (transportSecret && access.data) void openRoom({ id: access.data.roomId, code: access.data.code, protected: access.data.protected, transportSecret }).then(document => navigate(`/studio/${document.id}`)); if (access.data?.state === "declined" || access.data?.state === "expired") setError(access.data.state === "declined" ? "The room owner declined this join request." : "This join request expired. Please request access again."); }, [access.data?.state]);
  const card = !invite ? <><XCircle size={24} /><p className="eyebrow">Invite unavailable</p><h1>This room link is incomplete.</h1><p>Ask the room owner for a fresh invite code, then return to your workspace to request access.</p><button onClick={() => navigate("/")}>Return to workspace <ArrowRight size={15} /></button></> : requiresPassword && password.length < 8 ? <><KeyRound size={24} /><p className="eyebrow">Protected room · {invite.roomCode}</p><h1>Confirm the room password.</h1><p>The password is verified by the room registry before the owner ever receives a join request. It is never included in the invite link.</p><form onSubmit={event => { event.preventDefault(); const value = new FormData(event.currentTarget).get("password"); if (typeof value === "string") { setError(""); setPassword(value.trim()); setJoinRequested(true); } }}><label>Room password<input name="password" type="password" minLength={8} placeholder="Enter the owner’s password" autoFocus /></label><button type="submit">Verify and request access <ArrowRight size={15} /></button></form><small><ShieldCheck size={14} />The room key is released only after password verification and owner approval.</small></> : error ? <><XCircle size={24} /><p className="eyebrow">Request not completed</p><h1>Room access was not granted.</h1><p>{error}</p><button onClick={() => navigate("/")}>Return to workspace <ArrowRight size={15} /></button></> : <><Radio className="room-entry-pulse" size={24} /><p className="eyebrow">Secure room handshake · {invite.roomCode}</p><h1>{roomId ? "Your request is with the owner." : "Checking room access…"}</h1><p>{roomId ? "The owner can allow or decline your request from inside the document. This page will open the encrypted room automatically once access is approved." : "Verifying the room code and access policy with the metadata-only room registry."}</p><div className="room-entry-steps"><span className="done">1 · Code verified</span><span className={roomId ? "done" : "active"}>2 · {roomId ? "Owner notified" : "Checking policy"}</span><span>3 · Encrypted peer room</span></div></>;
  return <ProfileGate><main className="room-entry"><section className="room-entry-card">{card}</section><aside><span>PEERLOCK / ROOM ACCESS</span><div className="room-entry-orbit"><i /><i /><i /></div><strong>Private by design.<br />Shared by approval.</strong><p>Only approved guests receive the browser-to-browser transport secret. Document content remains outside the application server.</p></aside></main></ProfileGate>;
}
