import { ProfileGate } from "@/app/ProfileGate";
import { useWorkspace } from "@/app/WorkspaceProvider";
import { readInvite } from "@/features/room/invite";
import { trpc } from "@/lib/trpc";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";

export function RoomRoute() {
  const [, navigate] = useLocation(); const { profile, openRoom } = useWorkspace(); const invite = readInvite(); const [password, setPassword] = useState(() => { const code = readInvite()?.roomCode; return code ? sessionStorage.getItem(`peerlock-room-password:${code}`) ?? "" : ""; }); const [roomId, setRoomId] = useState(""); const [error, setError] = useState("");
  const request = trpc.room.requestJoin.useMutation({ onSuccess: value => { const transportSecret = value.state === "approved" && "transportSecret" in value ? value.transportSecret : undefined; if (transportSecret) void openRoom({ id: value.roomId, code: value.code, protected: value.protected, transportSecret }).then(document => navigate(`/studio/${document.id}`)); else setRoomId(value.roomId); }, onError: issue => setError(issue.message) });
  const access = trpc.room.access.useQuery({ roomId }, { enabled: Boolean(roomId), refetchInterval: 1000 });
  useEffect(() => { if (!profile || !invite || request.isPending || roomId) return; if (invite.protected && password.length < 8) return; request.mutate({ code: invite.roomCode, password: invite.protected ? password : undefined, identity: { name: profile.name || `Guest ${profile.id.slice(0, 4)}`, color: profile.color } }); if (invite.protected) sessionStorage.removeItem(`peerlock-room-password:${invite.roomCode}`); }, [profile?.id, invite?.roomCode, invite?.protected, password, roomId]);
  useEffect(() => { const transportSecret = access.data?.state === "approved" && "transportSecret" in access.data ? access.data.transportSecret : undefined; if (transportSecret && access.data) void openRoom({ id: access.data.roomId, code: access.data.code, protected: access.data.protected, transportSecret }).then(document => navigate(`/studio/${document.id}`)); if (access.data?.state === "declined" || access.data?.state === "expired") setError(access.data.state === "declined" ? "The room owner declined this join request." : "This join request expired. Please request access again."); }, [access.data?.state]);
  const content = !invite ? <div className="route-error"><h1>Room not opened</h1><p>This invite does not include a valid room code.</p><button onClick={() => navigate("/")}>Return to workspace</button></div> : invite.protected && password.length < 8 ? <div className="route-error"><p className="eyebrow">Password-protected room</p><h1>Enter the room password.</h1><p>The owner chose this password. It is verified by the room registry before a join request is created.</p><form onSubmit={event => { event.preventDefault(); const value = new FormData(event.currentTarget).get("password"); if (typeof value === "string") setPassword(value.trim()); }}><input name="password" type="password" placeholder="Room password" autoFocus /><button type="submit">Request access</button></form></div> : error ? <div className="route-error"><h1>Room not opened</h1><p>{error}</p><button onClick={() => navigate("/")}>Return to workspace</button></div> : <div className="route-error"><p className="eyebrow">Join request</p><h1>{roomId ? "Waiting for approval." : "Checking room access…"}</h1><p>{roomId ? "The room owner has been notified. This page will continue automatically if they approve." : "Verifying the room code and access policy."}</p></div>;
  return <ProfileGate><div className="route-loading">{content}</div></ProfileGate>;
}
