import { AppShell } from "@/components/AppShell";
import { PrivateMeshVisual } from "@/components/PrivateMeshVisual";
import { CheckCircle2, ClipboardList, Lightbulb, MessageCircleQuestion, Presentation, Quote, ShieldCheck } from "lucide-react";

const slides = [
  ["1", "Problem and motivation", "Centralised editors commonly process and retain document data on remote infrastructure. This project asks whether small-team collaboration can keep the data path in the browser."],
  ["2", "System architecture", "Show the three browser peers, Yjs replicas, IndexedDB, encrypted WebRTC data channels, and a signaling relay outside the document-content path."],
  ["3", "CRDT theory", "Explain independent replicas, operations, deterministic merging, and why concurrent edits need not overwrite each other."],
  ["4", "Offline-first workflow", "Demonstrate disabling network, making edits, restoring connectivity, and observing eventual convergence."],
  ["5", "Privacy model", "State the precise guarantee: application-server document storage is absent; data-channel transport is encrypted; connection metadata and endpoint compromise are limitations."],
  ["6", "Implementation demo", "Create a room, copy an invite, join it from a second browser, edit concurrently, inspect cursors and the mesh visualisation, then export Markdown."],
  ["7", "Evaluation and future work", "Discuss the ten-peer target, peer-mesh trade-offs, signaling availability, local device security, and future self-hosted or key-rotation extensions."],
];

const questions = [
  ["Why did you select a CRDT rather than operational transformation?", "CRDT replicas can merge operations after offline work without a central ordering authority. This aligns naturally with a peer-to-peer, local-first topology. Operational transformation is also viable but conventionally needs more coordination around transformation and ordering."],
  ["Is the project completely serverless?", "No. The document data path is peer-to-peer, but WebRTC commonly uses signaling to help peers exchange connection offers and answers. This project intentionally limits that role to ephemeral connection establishment rather than document storage."],
  ["How is document content protected while communicating?", "Yjs updates travel over WebRTC data channels, whose peer transport is encrypted. The y-webrtc room secret also protects sensitive information exchanged through untrusted signaling services. The browser does not post document content to the application server."],
  ["What happens if both users edit the same word while offline?", "Both Yjs replicas record valid CRDT updates locally. On reconnection the updates are exchanged and merged deterministically, producing one convergent shared state without a manual conflict dialog for ordinary text operations."],
  ["What are the limitations of IndexedDB persistence?", "It provides convenient durable browser-local persistence, not an application-managed encrypted vault. A person with access to an unlocked browser profile or a compromised endpoint may access local content."],
  ["Why is the room capped at ten participants?", "A peer mesh creates connection and bandwidth work in each browser. Keeping the room small makes the browser-to-browser model practical and easier to demonstrate reliably while preserving direct collaboration."],
];

export default function StudyPage() {
  return <AppShell><main className="mx-auto max-w-5xl pb-12"><header className="rounded-3xl border border-white/[0.09] bg-[#111722]/76 px-6 py-8 sm:px-9"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#B7AEFF]">MCA presentation and viva preparation</p><h1 className="mt-4 text-3xl font-semibold tracking-[-0.05em] text-white sm:text-[40px]">Defend the design with clarity.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#99A6BB]">This page turns the implementation into a concise presentation narrative and a technically accurate viva practice set.</p></header>
    <section className="mt-7 grid gap-5 lg:grid-cols-[0.95fr_1.05fr]"><PrivateMeshVisual /><div className="rounded-3xl border border-white/[0.08] bg-[#101620]/72 p-6"><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#7FE6CA]">Slide 2 — architecture visual</p><h2 className="mt-3 text-lg font-semibold text-white">Use this diagram while speaking.</h2><p className="mt-3 text-xs leading-6 text-[#919EB3]">“Each participant keeps an independent Yjs replica in the browser. IndexedDB preserves that replica offline. A signaling relay helps browsers discover each other, but it is outside the document-content path. After setup, updates travel over encrypted WebRTC data channels and converge through CRDT semantics.”</p><p className="mt-3 rounded-xl border border-[#B8AFFF]/15 bg-[#B8AFFF]/[0.06] px-3 py-2 text-[11px] leading-5 text-[#C9C2F4]">Speaker cue: point to the central vault first, then the peer lines; finally state the privacy boundary in one sentence.</p></div></section>
    <section className="mt-7 grid gap-5 md:grid-cols-3">{[{ icon: Presentation, label: "7-slide narrative", text: "A focused sequence for a 7–10 minute project demonstration." }, { icon: ClipboardList, label: "Live demo sequence", text: "Show local persistence, peer join, concurrent editing, and export." }, { icon: ShieldCheck, label: "Honest security claims", text: "Explain strong privacy boundaries without claiming impossible anonymity." }].map(item => <div key={item.label} className="rounded-2xl border border-white/[0.08] bg-[#101620]/72 p-5"><item.icon className="h-5 w-5 text-[#7FE6CA]" /><h2 className="mt-5 text-sm font-semibold text-white">{item.label}</h2><p className="mt-2 text-xs leading-5 text-[#8592A7]">{item.text}</p></div>)}</section>
    <section className="mt-7 rounded-3xl border border-white/[0.08] bg-[#101620]/72 p-6 sm:p-8"><div className="flex gap-3"><Presentation className="mt-0.5 h-5 w-5 text-[#7FE6CA]" /><div><h2 className="text-lg font-semibold text-white">Presentation outline</h2><p className="mt-1 text-sm text-[#8693A9]">Use one central architecture figure on slides 2 and 5; lead with a real browser demo rather than dense source code.</p></div></div><div className="mt-6 space-y-3">{slides.map(([number, title, note]) => <div key={number} className="grid gap-3 rounded-2xl border border-white/[0.06] bg-white/[0.025] p-4 sm:grid-cols-[36px_190px_1fr]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#A99FF7]/12 text-xs font-bold text-[#B8AFFF]">{number}</span><h3 className="pt-1 text-sm font-semibold text-[#E5EAF3]">{title}</h3><p className="text-xs leading-5 text-[#8B98AD]">{note}</p></div>)}</div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-3xl border border-[#7FE6CA]/15 bg-[#67E8C5]/[0.055] p-6"><Lightbulb className="h-5 w-5 text-[#7FE6CA]" /><h2 className="mt-4 text-lg font-semibold text-[#E1F9F1]">Demo checklist</h2><ol className="mt-4 space-y-3">{["Open the local document dashboard and state that documents are browser-resident.", "Host a private room and explain the visible room code versus hidden invite key.", "Open the same invite in a second browser profile or device.", "Type at the same time to show cursor awareness and CRDT merging.", "Toggle offline network, write locally, then reconnect and observe sync.", "Export the document to Markdown and show the in-app academic report."].map((item, index) => <li key={item} className="flex gap-3 text-xs leading-5 text-[#B3D7CC]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#7FE6CA]" /><span><strong className="mr-1 text-[#E4FAF4]">{index + 1}.</strong>{item}</span></li>)}</ol></div><div className="rounded-3xl border border-white/[0.08] bg-[#101620]/72 p-6"><div className="flex gap-3"><MessageCircleQuestion className="h-5 w-5 text-[#B7AEFF]" /><div><h2 className="text-lg font-semibold text-white">Expected viva questions</h2><p className="mt-1 text-sm text-[#8693A9]">Practice the reasoning, not only the definition.</p></div></div><div className="mt-5 space-y-3">{questions.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4"><summary className="cursor-pointer list-none pr-6 text-sm font-medium text-[#DFE6F2] marker:hidden">{question}<span className="float-right text-[#7FE6CA] group-open:rotate-45">+</span></summary><p className="mt-3 border-t border-white/[0.06] pt-3 text-xs leading-6 text-[#8C99AE]">{answer}</p></details>)}</div></div></section>
    <blockquote className="mt-7 rounded-2xl border-l-2 border-[#A99FF7] bg-[#A99FF7]/[0.055] px-5 py-4 text-sm leading-6 text-[#C8C2F1]"><Quote className="mr-2 inline h-4 w-4 text-[#B7AEFF]" />A good viva answer distinguishes **what the system guarantees** from **what it cannot guarantee**. State that content does not traverse the application server; do not claim that all network metadata disappears.</blockquote>
  </main></AppShell>;
}
