function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char] ?? char); }

function shell(input: { preheader: string; eyebrow: string; heading: string; body: string; action: string; actionHtml: string; footer: string }) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>Peerlock</title></head><body style="margin:0;background:#edf1eb;color:#14231e;font-family:Inter,Arial,sans-serif"><span style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">${escapeHtml(input.preheader)}</span><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#edf1eb"><tr><td align="center" style="padding:30px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#f9fbf7;border:1px solid #ced8d0"><tr><td style="padding:28px 30px 22px;background:#10221c"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td><span style="display:inline-block;padding:7px 8px;background:#c9fa65;color:#10221c;font-size:11px;font-weight:800;letter-spacing:.12em">PL</span><span style="margin-left:10px;color:#eef6f0;font-size:14px;font-weight:700;letter-spacing:.03em">PEERLOCK</span></td><td align="right" style="color:#c9fa65;font-size:10px;font-weight:700;letter-spacing:.12em">PRIVATE WORKSPACE</td></tr></table></td></tr><tr><td style="padding:38px 30px 32px"><p style="margin:0 0 13px;color:#08746b;font-size:11px;font-weight:800;letter-spacing:.12em">${escapeHtml(input.eyebrow)}</p><h1 style="margin:0;color:#14231e;font-size:36px;line-height:1.03;letter-spacing:-.055em;font-weight:750">${input.heading}</h1><div style="margin:23px 0;color:#52635a;font-size:15px;line-height:1.65">${input.body}</div><div style="margin:28px 0;padding:22px;border:1px solid #cdd9d0;background:#e4ece5;text-align:center">${input.actionHtml}</div><p style="margin:0;color:#687970;font-size:12px;line-height:1.55">${escapeHtml(input.footer)}</p></td></tr><tr><td style="padding:20px 30px;border-top:1px solid #d8dfd9;color:#76867e;font-size:11px;line-height:1.55">${escapeHtml(input.action)}<br><br>Peerlock keeps document content browser-local and encrypted between approved peers. This email concerns only your account access.</td></tr></table></td></tr></table></body></html>`;
}

export function verificationEmailTemplate(input: { username: string; otp: string }) {
  const username = escapeHtml(input.username); const otp = escapeHtml(input.otp);
  return { subject: "Your Peerlock verification code", text: `Hello ${input.username},\n\nYour Peerlock verification code is: ${input.otp}\n\nIt expires in 10 minutes. Never share this code with anyone.\n\nPeerlock`, html: shell({ preheader: `Your Peerlock verification code is ${input.otp}`, eyebrow: "ACCOUNT VERIFICATION", heading: "Confirm your<br>private workspace.", body: `<p style="margin:0">Hello ${username},</p><p style="margin:11px 0 0">Use the secure six-digit code below to verify your Peerlock account.</p>`, action: "This code expires in 10 minutes. Never share it with anyone.", actionHtml: `<div style="color:#0d2119;font-size:12px;font-weight:800;letter-spacing:.14em">YOUR SECURE CODE</div><div style="margin-top:9px;color:#10221c;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:35px;font-weight:800;letter-spacing:.23em">${otp}</div>`, footer: "This code expires in 10 minutes. If you did not create a Peerlock account, you can safely ignore this email." }) };
}

export function passwordResetEmailTemplate(input: { username: string; resetUrl: string }) {
  const username = escapeHtml(input.username); const safeUrl = escapeHtml(input.resetUrl);
  return { subject: "Reset your Peerlock password", text: `Hello ${input.username},\n\nUse this one-time link to reset your Peerlock password:\n${input.resetUrl}\n\nIt expires in 30 minutes.\n\nPeerlock`, html: shell({ preheader: "Securely reset your Peerlock password", eyebrow: "ACCOUNT RECOVERY", heading: "Restore access,<br>stay in control.", body: `<p style="margin:0">Hello ${username},</p><p style="margin:11px 0 0">A password reset was requested for your Peerlock account. Use the secure link below to choose a new password.</p>`, action: "This reset link expires in 30 minutes and can be used once. If you did not request it, you can safely ignore this email.", actionHtml: `<a href="${safeUrl}" style="display:inline-block;padding:14px 19px;background:#10221c;color:#f4fbf5;text-decoration:none;font-size:13px;font-weight:800;letter-spacing:.01em">Reset my password&nbsp; →</a><p style="margin:14px 0 0;color:#65766d;font-size:11px">For security, this link is valid for 30 minutes.</p>`, footer: "If the button does not open, copy the reset link from the plain-text version of this email." }) };
}
