import { and, desc, eq, gt, inArray, isNull, or } from "drizzle-orm";
import { randomUUID } from "node:crypto";
import { peerlockAccountSessions, peerlockAccounts, peerlockAdminAuditLogs, peerlockAnnouncements, peerlockGuestSessions, peerlockRoomMemberships, peerlockRooms } from "../drizzle/schema";
import { getDb } from "./db";
import { configuredSuperAdminEmail, isSuperAdminEmail } from "./adminAuthorization";

type AdminActor = { id: string; email: string; username: string; emailVerifiedAt: Date | null; suspendedAt?: Date | null };
export function requireSuperAdmin(account: AdminActor | null | undefined) {
  if (!account) throw new Error("Sign in to open the admin control center.");
  if (!account.emailVerifiedAt) throw new Error("Verify the configured admin email before opening the control center.");
  if (account.suspendedAt) throw new Error("This account is suspended.");
  if (!configuredSuperAdminEmail()) throw new Error("The super-admin identity is not configured on the server.");
  if (!isSuperAdminEmail(account.email)) throw new Error("This account is not authorized for the super-admin control center.");
  return account;
}
async function dbOrThrow() { const db = await getDb(); if (!db) throw new Error("Admin metadata service is unavailable."); return db; }
async function audit(actorId: string, action: string, targetType: string, targetId: string | null, summary: string) { const db = await dbOrThrow(); await db.insert(peerlockAdminAuditLogs).values({ id: randomUUID(), actorAccountId: actorId, action, targetType, targetId, summary }); }

export async function adminOverview() {
  const db = await dbOrThrow();
  const [accounts, verified, suspended, rooms, activeAnnouncements, audits] = await Promise.all([
    db.select().from(peerlockAccounts), db.select().from(peerlockAccounts).where(isNull(peerlockAccounts.emailVerifiedAt)), db.select().from(peerlockAccounts).where(gt(peerlockAccounts.suspendedAt, new Date(0))), db.select().from(peerlockRooms), db.select().from(peerlockAnnouncements).where(and(eq(peerlockAnnouncements.active, true), or(isNull(peerlockAnnouncements.expiresAt), gt(peerlockAnnouncements.expiresAt, new Date())))), db.select().from(peerlockAdminAuditLogs).orderBy(desc(peerlockAdminAuditLogs.createdAt)).limit(8),
  ]);
  return { configured: Boolean(configuredSuperAdminEmail()), metrics: { accounts: accounts.length, unverified: verified.length, suspended: suspended.length, rooms: rooms.length, activeAnnouncements: activeAnnouncements.length }, recentAudits: audits.map(row => ({ id: row.id, action: row.action, targetType: row.targetType, targetId: row.targetId, summary: row.summary, createdAt: row.createdAt })) };
}
export async function adminListAccounts() { const db = await dbOrThrow(); const accounts = await db.select({ id: peerlockAccounts.id, email: peerlockAccounts.email, username: peerlockAccounts.username, emailVerifiedAt: peerlockAccounts.emailVerifiedAt, createdAt: peerlockAccounts.createdAt, lastSignedInAt: peerlockAccounts.lastSignedInAt, suspendedAt: peerlockAccounts.suspendedAt, suspensionReason: peerlockAccounts.suspensionReason }).from(peerlockAccounts).orderBy(desc(peerlockAccounts.createdAt)); return accounts.map(account => ({ ...account, isSuperAdmin: isSuperAdminEmail(account.email) })); }
export async function adminSetAccountSuspension(actor: AdminActor, input: { accountId: string; suspended: boolean; reason?: string }) {
  const db = await dbOrThrow(); const [target] = await db.select().from(peerlockAccounts).where(eq(peerlockAccounts.id, input.accountId)).limit(1); if (!target) throw new Error("Account was not found."); if (isSuperAdminEmail(target.email)) throw new Error("The configured super-admin account cannot be suspended.");
  const reason = input.reason?.trim().slice(0, 240) || null;
  await db.update(peerlockAccounts).set({ suspendedAt: input.suspended ? new Date() : null, suspensionReason: input.suspended ? reason : null }).where(eq(peerlockAccounts.id, target.id));
  if (input.suspended) { await db.delete(peerlockAccountSessions).where(eq(peerlockAccountSessions.accountId, target.id)); const sessions = await db.select({ id: peerlockGuestSessions.id }).from(peerlockGuestSessions).where(eq(peerlockGuestSessions.accountId, target.id)); if (sessions.length) await db.update(peerlockRoomMemberships).set({ status: "declined", requestExpiresAt: null }).where(inArray(peerlockRoomMemberships.sessionId, sessions.map(session => session.id))); }
  await audit(actor.id, input.suspended ? "account.suspended" : "account.restored", "account", target.id, input.suspended ? "Account suspended and active account sessions revoked." : "Account restored."); return { success: true as const };
}
export async function adminListRooms() { const db = await dbOrThrow(); const rooms = await db.select({ id: peerlockRooms.id, code: peerlockRooms.code, protected: peerlockRooms.passwordHash, createdAt: peerlockRooms.createdAt, lastActivityAt: peerlockRooms.lastActivityAt }).from(peerlockRooms).orderBy(desc(peerlockRooms.lastActivityAt)); const memberships = await db.select({ id: peerlockRoomMemberships.id, roomId: peerlockRoomMemberships.roomId, displayName: peerlockRoomMemberships.displayName, status: peerlockRoomMemberships.status, lastSeenAt: peerlockRoomMemberships.lastSeenAt }).from(peerlockRoomMemberships); return rooms.map(room => { const members = memberships.filter(item => item.roomId === room.id); return { id: room.id, code: room.code, protected: Boolean(room.protected), createdAt: room.createdAt, lastActivityAt: room.lastActivityAt, memberships: { approved: members.filter(item => item.status === "approved").length, pending: members.filter(item => item.status === "pending").length, entries: members.map(item => ({ id: item.id, displayName: item.displayName, status: item.status, lastSeenAt: item.lastSeenAt })) }, privacy: "Metadata only — document, chat, password hash, and transport secret are never returned." }; }); }
export async function adminRevokeMembership(actor: AdminActor, input: { roomId: string; membershipId: string }) { const db = await dbOrThrow(); const [membership] = await db.select().from(peerlockRoomMemberships).where(and(eq(peerlockRoomMemberships.id, input.membershipId), eq(peerlockRoomMemberships.roomId, input.roomId))).limit(1); if (!membership) throw new Error("Room membership was not found."); await db.update(peerlockRoomMemberships).set({ status: "declined", requestExpiresAt: null }).where(eq(peerlockRoomMemberships.id, membership.id)); await audit(actor.id, "room.membership_revoked", "room_membership", membership.id, "Room registry access revoked for one membership."); return { success: true as const }; }
export async function adminDeleteRoom(actor: AdminActor, roomId: string) { const db = await dbOrThrow(); const [room] = await db.select({ id: peerlockRooms.id }).from(peerlockRooms).where(eq(peerlockRooms.id, roomId)).limit(1); if (!room) throw new Error("Room was not found."); await db.delete(peerlockRoomMemberships).where(eq(peerlockRoomMemberships.roomId, roomId)); await db.delete(peerlockRooms).where(eq(peerlockRooms.id, roomId)); await audit(actor.id, "room.registry_deleted", "room", roomId, "Room registry metadata and memberships deleted. Existing direct peers may persist until reconnect."); return { success: true as const }; }
export async function adminCreateAnnouncement(actor: AdminActor, input: { title: string; message: string; tone: string; expiresAt?: Date | null }) { const db = await dbOrThrow(); const id = randomUUID(); await db.insert(peerlockAnnouncements).values({ id, title: input.title.trim().slice(0, 120), message: input.message.trim().slice(0, 480), tone: input.tone, createdByAccountId: actor.id, expiresAt: input.expiresAt ?? null }); await audit(actor.id, "announcement.created", "announcement", id, "Created a site-wide operational announcement."); return { id }; }
export async function adminListAnnouncements() { const db = await dbOrThrow(); return db.select({ id: peerlockAnnouncements.id, title: peerlockAnnouncements.title, message: peerlockAnnouncements.message, tone: peerlockAnnouncements.tone, active: peerlockAnnouncements.active, createdAt: peerlockAnnouncements.createdAt, expiresAt: peerlockAnnouncements.expiresAt }).from(peerlockAnnouncements).orderBy(desc(peerlockAnnouncements.createdAt)); }
export async function adminSetAnnouncementActive(actor: AdminActor, id: string, active: boolean) { const db = await dbOrThrow(); await db.update(peerlockAnnouncements).set({ active }).where(eq(peerlockAnnouncements.id, id)); await audit(actor.id, active ? "announcement.activated" : "announcement.deactivated", "announcement", id, active ? "Announcement activated." : "Announcement deactivated."); return { success: true as const }; }
export async function activeAnnouncements() { const db = await dbOrThrow(); return db.select({ id: peerlockAnnouncements.id, title: peerlockAnnouncements.title, message: peerlockAnnouncements.message, tone: peerlockAnnouncements.tone, expiresAt: peerlockAnnouncements.expiresAt }).from(peerlockAnnouncements).where(and(eq(peerlockAnnouncements.active, true), or(isNull(peerlockAnnouncements.expiresAt), gt(peerlockAnnouncements.expiresAt, new Date())))).orderBy(desc(peerlockAnnouncements.createdAt)).limit(3); }
export async function adminAuditTrail() { const db = await dbOrThrow(); return db.select({ id: peerlockAdminAuditLogs.id, action: peerlockAdminAuditLogs.action, targetType: peerlockAdminAuditLogs.targetType, targetId: peerlockAdminAuditLogs.targetId, summary: peerlockAdminAuditLogs.summary, createdAt: peerlockAdminAuditLogs.createdAt }).from(peerlockAdminAuditLogs).orderBy(desc(peerlockAdminAuditLogs.createdAt)).limit(120); }
