import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from "@/components/ui/command";
import { BookOpen, FilePlus2, FolderOpen, Search, Settings2, ShieldCheck, UserRound } from "lucide-react";
import { useEffect } from "react";
import "./peer-command-palette.css";

type PeerCommandPaletteProps = { open: boolean; onOpenChange: (open: boolean) => void; isAdmin: boolean; onNavigate: (path: string) => void; onCreateDocument: () => Promise<void>; onToggleSettings: () => void };

export function PeerCommandPalette({ open, onOpenChange, isAdmin, onNavigate, onCreateDocument, onToggleSettings }: PeerCommandPaletteProps) {
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); onOpenChange(!open); } }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [open, onOpenChange]);
  const run = (action: () => void | Promise<void>) => { onOpenChange(false); void action(); };
  return <CommandDialog open={open} onOpenChange={onOpenChange} title="PeerLock command palette" description="Quick navigation and workspace actions" className="peer-command-dialog"><div className="peer-command-heading"><span><Search size={16} />Quick actions</span><kbd>ESC</kbd></div><CommandInput placeholder="Search workspace actions…" /><CommandList><CommandEmpty>No matching action.</CommandEmpty><CommandGroup heading="Workspace"><CommandItem value="new document create note" onSelect={() => run(onCreateDocument)}><FilePlus2 /><span>New private document</span><CommandShortcut>N</CommandShortcut></CommandItem><CommandItem value="workspace home documents" onSelect={() => run(() => onNavigate("/"))}><FolderOpen /><span>Open workspace</span><CommandShortcut>G W</CommandShortcut></CommandItem></CommandGroup><CommandSeparator /><CommandGroup heading="Navigate"><CommandItem value="learning academy guide" onSelect={() => run(() => onNavigate("/academy"))}><BookOpen /><span>Learning kit</span><CommandShortcut>G L</CommandShortcut></CommandItem><CommandItem value="settings preferences appearance" onSelect={() => run(onToggleSettings)}><Settings2 /><span>Settings</span><CommandShortcut>G S</CommandShortcut></CommandItem><CommandItem value="account sign in profile" onSelect={() => run(() => onNavigate("/account/sign-in"))}><UserRound /><span>Account</span><CommandShortcut>G A</CommandShortcut></CommandItem>{isAdmin ? <CommandItem value="admin control center" onSelect={() => run(() => onNavigate("/admin"))}><ShieldCheck /><span>Control center</span><CommandShortcut>G C</CommandShortcut></CommandItem> : null}</CommandGroup></CommandList><div className="peer-command-footer"><span>↑↓ to navigate</span><span>↵ to select</span><span>Esc to close</span></div></CommandDialog>;
}
